<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class PhimSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('phim')->insert([
            [
                'ID_Phim' => 1,
                'TenPhim' => 'Từ Vũ Trụ John Wick: Ballerina',
                'Slug' => 'tu-vu-tru-john-wick-ballerina',
                'NhaSanXuat' => 'Basil Iwanyk, Erica Lee, Chad Stahelski',
                'DaoDien' => 'Len Wiseman',
                'DienVien' => 'Ana De Armas, Keanu Reeves, Norman Reedus',
                'ThoiLuong' => 125,
                'NgayKhoiChieu' => now()->format('Y-m-d'),
                'NgayKetThuc' => now()->addDays(10)->format('Y-m-d'),
                'MoTaPhim' => 'Lấy bối cảnh giữa sự kiện của Sát thủ John Wick: Phần 3 – Chuẩn Bị Chiến Tranh, bộ phim Từ Vũ Trụ John Wick: Ballerina theo chân Eve Macarro (thủ vai bởi Ana de Armas) trên hành trình trả thù cho cái chết của gia đình mình, dưới sự huấn luyện của tổ chức tội phạm Ruska Roma.',
                'Trailer' => 'https://youtu.be/s35jjZBStJM',
                'HinhAnh' => 'phim/1749487967_ballerina-500_1748252018554.jpg',
                'DoTuoi' => 'T16 (16+)',
                'DoHoa' => '3D',
                'QuocGia' => 'Tây Ban Nha',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ID_Phim' => 2,
                'TenPhim' => 'Mưa Lửa - Anh Trai Vượt Ngàn Chông Gai Movie',
                'Slug' => 'mua-lua-anh-trai-vuot-ngan-chong-gai-movie',
                'NhaSanXuat' => '1Production, Ganga Studios',
                'DaoDien' => 'Đinh Hà Uyên Thư',
                'DienVien' => 'Gia Tộc Anh Tài',
                'ThoiLuong' => 125,
                'NgayKhoiChieu' => now()->format('Y-m-d'),
                'NgayKetThuc' => now()->addDays(10)->format('Y-m-d'),
                'MoTaPhim' => 'Mưa Lửa – phim tư liệu về hành trình 33 anh tài tham gia chương trình Anh Trai Vượt Ngàn Chông Gai 2024. Những câu chuyện chưa từng lên sóng, những chông gai ngoài đời thực, những khó khăn và những niềm vui...  Vũ trụ đã sắp đặt, phải là 33 con người này, số phận đã định đoạt, phải là 33 Anh Tài này để tạo nên mùa Anh Trai Vượt Ngàn Chông Gai đầu tiên! Hành trình của Anh Trai Vượt Ngàn Chông Gai 2024 là những cơn “mưa lửa”, chứa đựng niềm tin, niềm hy vọng và sự hồi sinh trong cuộc sống. Lửa hun đúc tinh thần, mưa tái sinh tâm hồn, và vì thế, những cơn “mưa lửa” trên hành trình vượt ngàn chông gai đã thực sự làm bùng lên khát khao mãnh liệt được yêu, được sống, được cống hiến của bất kỳ ai, nghệ sĩ hay khán giả. Đó là những mạch cảm xúc tinh tế mà 33 Anh Tài đã thắp lên, đã truyền đi và đã giữ mãi sức nóng đó trong trái tim hàng triệu người hâm mộ.',
                'Trailer' => 'https://youtu.be/pXGutUiI7Pw',
                'HinhAnh' => 'phim/1749487926_mua-lua---anh-trai-vuot-ngan-chong-gai-movie-2_1746078168404.jpg',
                'DoTuoi' => 'K',
                'DoHoa' => '3D',
                'QuocGia' => 'Việt Nam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ID_Phim' => 3,
                'TenPhim' => 'Lilo & Stitch',
                'Slug' => 'lilo-stitch',
                'NhaSanXuat' => 'Walt Disney Pictures',
                'DaoDien' => 'Dean Fleischer Camp, Maia Kealoha, Sydney Elizabeth, Agudong Billy Magnussen',
                'DienVien' => 'Mizuta Wasabi, Ogata Megumi, Kakazu Yumi',
                'ThoiLuong' => 1,
                'NgayKhoiChieu' => now()->format('Y-m-d'),
                'NgayKetThuc' => now()->addDays(10)->format('Y-m-d'),
                'MoTaPhim' => 'Cùng nhóm bạn Doraemon trở về châu Âu thế kỉ 13, vào thế giới trong tranh ở phim mới Doraemon The Movie: Nobita\'s Art World Tales. Chuyến phiêu lưu mạo hiểm vượt thời không tới công quốc Artoria sẽ mang đến bất ngờ gì?',
                'Trailer' => 'https://youtu.be/A7jw6CZ7sAY',
                'HinhAnh' => 'phim/1749487915_lilo-500_1747389395062.jpg',
                'DoTuoi' => 'P',
                'DoHoa' => null,
                'QuocGia' => 'Nhật Bản',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ID_Phim' => 4,
                'TenPhim' => 'Nhiệm Vụ: Bất Khả Thi - Nghiệp Báo Cuối Cùng',
                'Slug' => 'nhiem-vu-bat-kha-thi-nghiep-bao-cuoi-cung',
                'NhaSanXuat' => 'Paramount Pictures, Skydance Media',
                'DaoDien' => 'Christopher McQuarrie',
                'DienVien' => 'Tom Cruise Hayley Atwell Vanessa Kirby Ving Rhames Simon Pegg',
                'ThoiLuong' => 169,
                'NgayKhoiChieu' => now()->format('Y-m-d'),
                'NgayKetThuc' => now()->addDays(10)->format('Y-m-d'),
                'MoTaPhim' => 'Phim mới Mission: Impossible - The Final Reckoning/ Nhiệm Vụ: Bất Khả Thi - Nghiệp Báo Cuối Cùng là phần cuối của loạt phim hành động lừng danh do Tom Cruise thủ vai chính. Đặc vụ IMF lừng danh - Ethan Hunt trở lại với Nhiệm Vụ Bất Khả Thi Cuối Cùng. Liệu anh và các cộng sự có chiến thắng đối thủ hùng mạnh nhất - trí thông minh nhân tạo?',
                'Trailer' => 'https://youtu.be/XZHBlBNSkKM',
                'HinhAnh' => 'phim/1749487952_mi8-500_1746763198482.jpg',
                'DoTuoi' => 'T13 (13+)',
                'DoHoa' => '3D',
                'QuocGia' => 'Hàn Quốc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ID_Phim' => 5,
                'TenPhim' => 'Elio Cậu Bé Đến Từ Trái Đất',
                'Slug' => 'elio-cau-be-den-tu-trai-dat',
                'NhaSanXuat' => 'PIXAR, Walt Disney Pictures',
                'DaoDien' => 'Adrian Molina, Madeline Sharafian, Domee Shi',
                'DienVien' => 'Yonas Kibreab, Zoe Saldana, Brad Garrett',
                'ThoiLuong' => 97,
                'NgayKhoiChieu' => now()->format('Y-m-d'),
                'NgayKetThuc' => now()->addDays(10)->format('Y-m-d'),
                'MoTaPhim' => 'Elio là một cậu bé đam mê vũ trụ với trí tưởng tượng phong phú. Một hôm, cậu bất ngờ phải tham gia một cuộc phiêu lưu ngoài vũ trụ, nơi cậu phải xây dựng mối quan hệ mới với các dạng sống ngoài hành tinh. Elio phải vượt qua cuộc chiến ở quy mô liên thiên hà và khám phá ra con người thực sự của mình. Trong cuộc phiêu lưu dở khóc dở cười trên màn ảnh rộng của Pixar, Elio – cậu bé mê mẩn người ngoài hành tinh – bất ngờ bị cuốn vào Liên Hiệp Thiên Hà, một vũ trụ liên hành tinh đầy kỳ diệu, nơi quy tụ các loài sinh vật thông minh khắp thiên hà. Trớ trêu thay, Elio lại bị hiểu nhầm là người đứng đầu Trái Đất. Giờ đây, cậu phải vượt qua những rắc rối mang quy mô vũ trụ, kết nối với những người bạn không ngờ tới, và tìm cách biến giấc mơ lớn nhất đời mình thành hiện thực.',
                'Trailer' => 'https://youtu.be/rdzfDoJcrxA',
                'HinhAnh' => 'phim/1750560631_elio-750_1750220019303.jpg',
                'DoTuoi' => 'P',
                'DoHoa' => '2D',
                'QuocGia' => 'Mỹ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ID_Phim' => 6,
                'TenPhim' => '28 Năm Sau Tận Thế',
                'Slug' => '28-nam-sau-tan-the',
                'NhaSanXuat' => 'Columbia Pictures',
                'DaoDien' => 'Ryota Kondo',
                'DienVien' => 'Aaron Taylor-Johnson, Ralph Fiennes, Alfie Williams',
                'ThoiLuong' => 114,
                'NgayKhoiChieu' => now()->format('Y-m-d'),
                'NgayKetThuc' => now()->addDays(10)->format('Y-m-d'),
                'MoTaPhim' => 'Cơn ác mộng chưa kết thúc. Virus trở lại, kéo theo bóng tối bao trùm nước Anh. Một hành trình sinh tử: cậu bé tìm kiếm bác sĩ để cứu mẹ mình, băng qua vùng đất chết chóc đầy xác sống tiến hóa và những kẻ nguy hiểm ẩn sau gương mặt tử tế. Liệu niềm hy vọng cuối cùng có đủ để cứu họ khỏi vực thẳm tuyệt vọng?',
                'Trailer' => 'https://youtu.be/uyKdDzo6rSU',
                'HinhAnh' => 'phim/1750581769_28-year-later-500_1750407074215.jpg',
                'DoTuoi' => 'T18 (18+)',
                'DoHoa' => null,
                'QuocGia' => 'Mỹ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ID_Phim' => 7,
                'TenPhim' => 'F1®',
                'Slug' => 'F1',
                'NhaSanXuat' => 'Apple Studios',
                'DaoDien' => 'Joseph Kosinski',
                'DienVien' => 'Brad Pitt, Simone Ashley, Javier Bardem',
                'ThoiLuong' => 156,
                'NgayKhoiChieu' => now()->format('Y-m-d'),
                'NgayKetThuc' => now()->addDays(10)->format('Y-m-d'),
                'MoTaPhim' => 'F1® kể về Sonny Hayes (Brad Pitt) được mệnh danh là "Huyền thoại chưa từng được gọi tên" là ngôi sao sáng giá nhất của FORMULA 1 trong những năm 1990 cho đến khi một vụ tai nạn trên đường đua suýt nữa đã kết thúc sự nghiệp của anh.. Ba mươi năm sau, Sonny trở thành một tay đua tự do, cho đến khi người đồng đội cũ của anh, Ruben Cervantes (Javier Bardem), chủ sở hữu một đội đua F1 đang trên bờ vực sụp đổ, tìm đến anh. Ruben thuyết phục Sonny quay lại với F1® để có một cơ hội cuối cùng cứu lấy đội và khẳng định mình là tay đua xuất sắc nhất thế giới. Anh sẽ thi đấu cùng Joshua Pearce (Damson Idris), tay đua tân binh đầy tham vọng của đội, người luôn muốn tạo ra tốc độ của riêng mình. Tuy nhiên, khi động cơ gầm rú, quá khứ của Sonny sẽ đuổi theo anh và anh nhận ra rằng trong F1, người đồng đội chính là đối thủ cạnh tranh lớn nhất—và con đường chuộc lại lỗi lầm không phải là điều có thể đi một mình. F1® suất chiếu sớm 25-26.06 (không áp dụng Movie Voucher), khởi chiếu chính thức 27.06.2025 tại các rạp chiếu phim toàn quốc.',
                'Trailer' => 'https://youtu.be/llrZvUGzUUk',
                'HinhAnh' => 'phim/phimData_1.jpg',
                'DoTuoi' => 'T16 (16+)',
                'DoHoa' => null,
                'QuocGia' => 'Mỹ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ID_Phim' => 8,
                'TenPhim' => 'Ma không đầu',
                'Slug' => 'ma-khong-dau',
                'NhaSanXuat' => 'Ai Media Films, Galaxy Studio',
                'DaoDien' => 'Bùi Văn Hải',
                'DienVien' => 'Ngô Kiến Huy, Tiến Luật, NSND Hồng Vân, Hữu Châu, Đại Nghĩa',
                'ThoiLuong' => 115,
                'NgayKhoiChieu' => now()->format('Y-m-d'),
                'NgayKetThuc' => now()->addDays(10)->format('Y-m-d'),
                'MoTaPhim' => 'Bộ đôi Tiến Luật và Ngô Kiến Huy, với nghề nghiệp "độc lạ" hốt xác và lái xe cứu thương, hứa hẹn mang đến những tràng cười không ngớt cho khán giả qua hành trình tìm xác có một không hai trên màn ảnh Việt. Nhờ sự trợ giúp của thế lực tâm linh, họ không chỉ đối mặt với những tình huống "dở khóc dở cười" mà còn khám phá ra những bí mật rợn người ẩn sau những thi thể. Liệu họ có hoàn thành nhiệm vụ "khó nhằn" này hay sẽ gặp phải những "biến cố" nào?',
                'Trailer' => 'https://youtu.be/_kUhOI59OXU',
                'HinhAnh' => 'phim/phimData_2.jpg',
                'DoTuoi' => 'T18 (18+)',
                'DoHoa' => null,
                'QuocGia' => 'Việt Nam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ID_Phim' => 9,
                'TenPhim' => 'Halabala: Rừng Ma Tế Xác',
                'Slug' => 'halabala-rung-ma-te-xac',
                'NhaSanXuat' => 'BrandThink Cinema',
                'DaoDien' => 'Eakasit Thairaat',
                'DienVien' => 'Ter Chantavit Nuttanicha Dungwattanawanich',
                'ThoiLuong' => 90,
                'NgayKhoiChieu' => now()->format('Y-m-d'),
                'NgayKetThuc' => now()->addDays(10)->format('Y-m-d'),
                'MoTaPhim' => 'Thanh tra Dan – kẻ mang biệt danh rùng rợn “Dan Trăm Xác” – là một cảnh sát liều mạng, nổi tiếng với quá khứ đẫm máu và những phi vụ bất chấp luật lệ. Sau một sai lầm kinh hoàng trong lúc thực hiện nhiệm vụ, Dan bị giáng chức và chuyển công tác về vùng hẻo lánh. Với nổ lực để có cơ hội trở lại Bangkok – anh cần bắt được Tup Ta Fai: tên trùm tội phạm loạn trí vừa trốn khỏi ngục, hiện đang ẩn náu trong khu rừng cấm Halabala. Thế nhưng, Halabala không phải một khu rừng bình thường. Nơi đây bị nguyền rủa bởi truyền thuyết quỷ Bataya và Batow – tộc người ăn thịt từng sống trong rừng sâu và đang nuôi dưỡng con quỷ Bataya bằng hận thù và xác người. Trong cuộc truy đuổi đẫm máu giữa rừng thiêng, Dan không chỉ phải đối đầu với Ta Fai, mà còn bị ám ảnh bởi những tiếng gọi ma quái, những ám ảnh dị dạng và nỗi sợ sâu kín nhất của chính anh. Khi vợ anh – Vi – đang mang thai sắp sinh và lạc giữa rừng, Dan buộc phải chọn: công lý… hay sự an toàn của gia đình mình?',
                'Trailer' => 'https://youtu.be/svKkKMHM8UU',
                'HinhAnh' => 'phim/phimData_3.jpg',
                'DoTuoi' => 'T18 (18+)',
                'DoHoa' => null,
                'QuocGia' => 'Thái Lan',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}